name: build Typst document
on: [push, workflow_dispatch, pull_request]

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: main.pdf
