name: compile Typst documents
on:
  workflow_dispatch:
  push:
    tags:
    - '**'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Typst
      uses: lkndl/typst-action@main
      with:
        source_file: main.typ
        output_file: tests/main.pdf
        options: |
            --font-path
            modules/fonts
    - name: Check existence of output file
      run: |
        test -e "tests/main.pdf"
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: tests/*.pdf
